apiVersion: v1
kind: Namespace
metadata:
  name: test
---
kind: Service
apiVersion: v1
metadata:
  name: nginx-svc
  namespace: test
spec:
  selector:
    app: nginx
  ports:
    - protocol: "HTTP"
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: test
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: my-route
  namespace: test
spec:
  parentRefs:
  - kind: Gateway
    name: my-gateway
    namespace: gateway-ns
  rules:
  - matches:
    - path:
        value: /
    backendRefs:
    - name: nginx-svc
      kind: Service
      group: ""
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: Gateway
metadata:
  name: my-gateway
  namespace: test
spec:
  gatewayClassName: gke-l7-gxlb
  listeners:
  - name: http
    protocol: HTTP
    port: 80
---
apiVersion: networking.gke.io/v1
kind: HealthCheckPolicy
metadata:
  name: nginx-healthcheck
  namespace: test
spec:
  default:
    checkIntervalSec: 30
    config:
      httpHealthCheck:
        portSpecification: USE_SERVING_PORT
        requestPath: /
      type: HTTP
    healthyThreshold: 1
    timeoutSec: 2
    unhealthyThreshold: 3
  targetRef:
    group: ""
    kind: Service
    name: nginx-svc
