name: nginx
on:
  workflow_dispatch:  # Enable manual triggering

env:
  PROJECT_ID: clever-dolphin-443009-c9
  GKE_LOCATION: asia-south1 # TODO: update region of the Artifact Registry
  GKE_CLUSTER: demo    # TODO: update to cluster name
  # GKE_ZONE: asia-south1-a   # TODO: update to cluster zone
  # DEPLOYMENT_NAME: engro-xms-dev-user-pod # TODO: update to deployment name
  # REPOSITORY: engro-xms-dev-frontend # TODO: update to Artifact Registry docker repository
  IMAGE: nginx
  NAMESPACE: test

jobs:
  job_id:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    environment: test

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    # Authentication via Workload Identity Federation
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        project_id: $PROJECT_ID
        workload_identity_provider: 'projects/39570659251/locations/global/workloadIdentityPools/github-wif/providers/github-actions'

    - name: Docker configuration
      run: |-
        gcloud auth configure-docker \
        asia-south1-docker.pkg.dev
    - id: 'get-credentials'
      uses: 'google-github-actions/get-gke-credentials@v2'
      with:
        cluster_name: $GKE_CLUSTER
        location: $GKE_LOCATION
        project_id: $PROJECT_ID
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: |-
        kubectl apply -f nginx.yaml
    - name: checking pods
      run: |-
        kubectl get pods -n $NAMESPACE
